let appState=null;
const dayOrder=['Mon','Tue','Wed','Thu','Fri','Sat'];
async function api(path,opts={}){const r=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...opts});return r.json()}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',3500)}
function render(){if(!appState)return; const s=appState; document.getElementById('done').textContent=s.sessions.filter(x=>x.status==='completed').length;document.getElementById('missed').textContent=s.sessions.filter(x=>x.status==='missed').length;document.getElementById('total').textContent=s.sessions.length+10;document.getElementById('pdone').textContent=document.getElementById('progDone').textContent=document.getElementById('done').textContent;document.getElementById('planGoal').textContent=document.getElementById('progressGoal').textContent=s.goal;
 const week=document.getElementById('week');week.innerHTML=dayOrder.map((d,i)=>`<div class="day"><h4>${d}<b>${14+i}</b></h4>${s.sessions.filter(x=>x.day===d).map(x=>`<div class="session ${x.status}"><strong>${x.start} · ${x.topic}</strong>${x.activity}</div>`).join('')}</div>`).join('');
 const gapData=s.performance.map(p=>({...p,priority:(100-p.score)*.65+(100-p.confidence)*.35})).sort((a,b)=>b.priority-a.priority); const gaps=gapData.map((g,i)=>`<div class="gap"><div class="gaphead"><span><span class="tag ${i<2?'critical':i===2?'moderate':'minor'}">${i<2?'CRITICAL':i===2?'MODERATE':'MINOR'}</span>${g.topic}</span><b>${Math.round(g.score)}%</b></div><div class="bar"><i style="width:${g.score}%"></i></div></div>`).join('');document.getElementById('gaps').innerHTML=gaps;document.getElementById('progressGaps').innerHTML=gaps;
 document.getElementById('sessionList').innerHTML=s.sessions.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<div class="sessionrow"><div><b>${x.activity}</b><div class="meta">${x.day} · ${x.start} · ${x.topic} · ${x.status.toUpperCase()}</div></div>${['upcoming','rescheduled'].includes(x.status)?`<div><button onclick="setStatus('${x.id}','completed')">✓ Done</button><button onclick="setStatus('${x.id}','missed')">✕ Missed</button></div>`:''}</div>`).join('');
 const tr=document.getElementById('trace');tr.innerHTML=(s.agent_events?.length?s.agent_events:[{step:'READY',message:'Waiting for observation event...'}]).slice(0,7).map(e=>`<div class="traceitem"><b>${e.step}</b>${e.message}</div>`).join('');}
async function load(){appState=await api('/state');render()}
async function runAgent(){toast('Agent observing state → diagnosing gaps → retrieving → planning...');const r=await api('/run-agent',{method:'POST'});appState=r.state;render();toast('✓ Agent cycle complete. Plan verified and updated.');}
async function setStatus(id,status){await api('/session/'+id,{method:'POST',body:JSON.stringify({status})});appState=await api('/state');render();toast(status==='missed'?'Miss observed. Run Agent Cycle to adapt future activities.':'Completion recorded. Agent will use this signal next cycle.')}
function openModal(id){document.getElementById(id).classList.add('show')}function closeModal(id){document.getElementById(id).classList.remove('show')}
async function addConstraint(){const day=document.getElementById('blockDay').value,start=document.getElementById('blockStart').value;appState=await api('/block-time',{method:'POST',body:JSON.stringify({day,start})});closeModal('constraintModal');render();toast('New constraint observed. Replanning...');setTimeout(runAgent,400)}
async function saveGoalAndRun(){const body={goal:document.getElementById('goal').value,deadline:document.getElementById('deadline').value,weekly_hours_target:+document.getElementById('hours').value};appState=await api('/goal',{method:'POST',body:JSON.stringify(body)});render();await runAgent();showView('dashboard')}
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===id))}
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>showView(x.dataset.view));load();
